### ISSUE TITLE
Infinite request to api/calendar?year=2022

### ISSUE THREAD

**Issue by mesterum** [beatnik-ditty/advent-of-node#7]
On day 6 of year 2022 I get this infinite error in browser:
```
index-5d6c61a0.js:101 TypeError: Cannot read properties of null (reading 'days')
    at transformResponse (index-5d6c61a0.js:101:36267)
    at index-5d6c61a0.js:101:4709
    at l (index-5d6c61a0.js:99:37622)
    at Object.next (index-5d6c61a0.js:99:36926)
    at o (index-5d6c61a0.js:99:38616)
(anonymous) @ index-5d6c61a0.js:101
l @ index-5d6c61a0.js:99
(anonymous) @ index-5d6c61a0.js:99
o @ index-5d6c61a0.js:99
```
And without ceasing it requests to api/calendar?year=2022
I don't have a source map for a better error message.

**Comment by grahamdporter** [comment]
I'll look into adding some throttling on the retry loop. As far as your actual error, you should have a collection named "calendars" in your MongoDB instance. Does it have a 2022 calendar object, and, if so, what does it look like?

**Comment by beatnik-ditty** [comment]
I'll look into adding some throttling on the retry loop. As far as your actual error, you should have a collection named "calendars" in your MongoDB instance. Does it have a 2022 calendar object, and, if so, what does it look like?

**Comment by mesterum** [comment]
No. I have a calendars collection, but empty.

**Comment by beatnik-ditty** [comment]
My first thought is that, right now, the calendar object is only actually created if you're on the calendar page. Bit of an oversight on my part. What happens if you close then reopen Day 6?

**Comment by mesterum** [comment]
The same errors. The content of api/calendar?year=2022 is "null"

**Comment by mesterum** [comment]
now it's OK. I misunderstood "close then reopen Day 6". I navigated away and back with the browser button. After closing with your button, I got a calendar data

**Comment by beatnik-ditty** [comment]
That makes sense. I've reproduced the issue, should have a fix up soon. Thanks for reporting!

**Comment by beatnik-ditty** [comment]
The actual loop was caused by a malformed transformResponse implementation in `data-access-api`. Fixed the loop and cleaned up a few bits of logic to make future similar problems less likely.
